apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fast-api
  name: fast-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fast-api
  strategy: {}
  template:
    metadata:
      labels:
        app: fast-api
    spec:
      containers:
      - image: leoadev/fastapi-kubernetes-deployment
        name: fastapi-kubernetes-deployment
        ports:
        - containerPort: 8080
        resources: {}
status: {}
