apiVersion: v1
kind: Pod
metadata:
  labels:
    run: fast-api
  name: fast-api
spec:
  containers:
  - image: leoadev/fastapi-kubernetes-deployment
    name: fast-api
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    readinessProbe:
      httpGet:
        path: /
        port: 80
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
