apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: fast-api
  name: fast-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: fast-api
status:
  loadBalancer: {}
